services:
  - type: web
    name: rata-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CLIENT_ORIGIN
        value: https://rata.vercel.app
