const PHASES = {
  LOBBY: 'LOBBY',
  INITIAL_PEEK: 'INITIAL_PEEK',
  PLAYING: 'PLAYING',
  LAST_ROUND: 'LAST_ROUND',
  ENDED: 'ENDED',
};

const CARD_TYPES = {
  NUMBER: 'NUMBER',
  PEEK: 'PEEK',
  SWAP: 'SWAP',
  DRAW2: 'DRAW2',
};

const TURN_PHASES = {
  IDLE: 'IDLE',
  DREW_FROM_DECK: 'DREW_FROM_DECK',
  DREW_FROM_DISCARD: 'DREW_FROM_DISCARD',
  USING_POWER: 'USING_POWER',
  DRAW2_PENDING: 'DRAW2_PENDING',
};

module.exports = { PHASES, CARD_TYPES, TURN_PHASES };
